name: Update Metadata

on:
  workflow_dispatch:

jobs:
  update-metadata:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run metadata scraper
      run: |
        python scraper_metadata.py

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git

        if [[ `git status --porcelain` ]]; then
          git add metadata.csv
          git commit -m "🔄 Update metadata"
          git push origin main
        else
          echo "✅ No changes to commit"
        fi